network: aptos
folder: mainnet
repo: https://github.com/aptos-labs/aptos-core
node_version: 88bb502c81fbdbb194a64be1e62a10703d6bfa36
genesis_blob: https://github.com/aptos-labs/aptos-networks/raw/main/mainnet/genesis.blob
waypoint: https://github.com/aptos-labs/aptos-networks/raw/main/mainnet/waypoint.txt
p2p_port: 6180
p2p_port_vfn: 6182
api_port: 8080

# Build profile
build_profile: release

hotfix_binary_url: "https://github.com/aptos-labs/aptos-core/releases/download/aptos-node-v1.3.5/aptos-node-ubuntu-22-04.tgz"
