network: chihuahua
folder: ".chihuahuad"
daemon: chihuahuad
chain_id: chihuahua-1
node_version: v4.1.0
repo: https://github.com/ChihuahuaChain/chihuahua.git
genesis: "https://github.com/ChihuahuaChain/chihuahua/raw/main/mainnet/genesis.json"
peers: ""
seeds: "ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:12956,20e1000e88125698264454a884812746c2eb4807@seeds.lavenderfive.com:12956"
minimum_gas_price: "1uhuahua"
custom_port_prefix: 129
snap_rpc: "https://chihuahua-rpc.polkachu.com:443"

# [Optional] Snapshot
snapshot_hour: 0
snapshot_minute: 0
