network: cosmos
folder: ".gaia"
daemon: gaiad
chain_id: cosmoshub-4
node_version: v19.2.0
repo: "https://github.com/cosmos/gaia"
genesis: "https://github.com/cosmos/mainnet/blob/master/genesis/genesis.cosmoshub-4.json.gz?raw=true"
genesis_processing: gz
minimum_gas_price: "0.0025uatom"
seeds: "ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:14956"
custom_port_prefix: 149

snap_rpc: https://cosmos-rpc.polkachu.com:443

upgrade_name: v19

snapshot_url: https://snapshots.polkachu.com/snapshots/cosmos/cosmos_21902086.tar.lz4

go_release: go1.21.11
