network: gitopia
folder: ".gitopia"
daemon: gitopiad
chain_id: gitopia
node_version: v3.3.0
binary: https://server.gitopia.com/releases/Gitopia/gitopia/v3.3.0/gitopiad_3.3.0_linux_amd64.tar.gz
binary_processing: targz
repo: https://github.com/gitopia/gitopia
genesis: https://github.com/gitopia/mainnet/raw/master/genesis.tar.gz
genesis_processing: targz
seeds: "a4a69a62de7cb0feb96c239405aa247a5a258739@seeds.cros-nest.com:57656,ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:11356,babc3f3f7804933265ec9c40ad94f4da8e9e0017@seed.rhinostake.com:11356"
minimum_gas_price: "0.001utlore"
custom_port_prefix: 113

upgrade_name: v3.3.0

# StateSync
snap_rpc: "https://gitopia-rpc.polkachu.com:443"

snapshot_url: https://snapshots.polkachu.com/snapshots/gitopia/gitopia_9853808.tar.lz4
