network: juno
folder: ".juno"
daemon: junod
chain_id: juno-1
node_version: v22.0.1
repo: "https://github.com/CosmosContracts/juno"
genesis: "https://raw.githubusercontent.com/CosmosContracts/mainnet/main/juno-1/genesis.json"
seeds: "babc3f3f7804933265ec9c40ad94f4da8e9e0017@seed.rhinostake.com:12656,90b09362d9ce3845096c4938eea0dba682b0ad2c@juno-seed-new.blockpane.com:26656,20e1000e88125698264454a884812746c2eb4807@seeds.lavenderfive.com:12656"
minimum_gas_price: "0.0025ujuno"
custom_port_prefix: 126

# StateSync
snap_rpc: "https://juno-rpc.polkachu.com:443"

upgrade_name: v22

snapshot_url: https://snapshots.lavenderfive.com/snapshots/juno/latest.tar.lz4

# Horcrux
horcrux_group: horcrux_alpha
sentries:
  - "100.100.1.203"
  - "100.100.1.204"
