network: juno
folder: ".juno"
daemon: junod
chain_id: juno-1
node_version: v9.0.0
repo: "https://github.com/CosmosContracts/juno"
genesis: "https://raw.githubusercontent.com/CosmosContracts/mainnet/main/juno-1/genesis.json"
seeds: "22ee6e65e5e79cd0b970dd11e52761de8d1d6dfd@seeds.pupmos.network:2001,90b09362d9ce3845096c4938eea0dba682b0ad2c@juno-seed-new.blockpane.com:26656"
minimum_gas_price: "0.0025ujuno"
custom_port_prefix: 126
snap_rpc: "https://juno-rpc.polkachu.com:443"

# [Optional] Snapshot
snapshot_hour: 0
snapshot_minute: 0
