network: konstellation
folder: '.knstld'
daemon: knstld
chain_id: darchub
node_version: v0.5.0
repo: https://github.com/konstellation/konstellation
genesis: 'https://raw.githubusercontent.com/Konstellation/konstellation/master/config/genesis.json'
peers: ''
seeds: '00f7f4506d84f9d1458201946e1194564b444ce0@node14.konstellation.tech:26656,06fed4bbe81ead6073a7254e860331179af74f4c@node3.konstellation.tech:26656,dbb7589202f6c751f2b93c6bbcd0e660676ab91c@node12.konstellation.tech:26656,0f4eef8db37ec7ef9f6d3324689db2847ee8f795@node10.konstellation.tech:26656'
minimum_gas_price: '0.0001udarc'
custom_port_prefix: 133

# [Optional] Snapshot
snapshot_hour: 3
snapshot_minute: 30
