network: lava
folder: ".lava"
daemon: lavad
chain_id: lava-mainnet-1
node_version: v1.0.1
repo: https://github.com/lavanet/lava.git
genesis: https://storage.googleapis.com/lavanet-public-asssets/tge/genesis.json
seeds: "ebacd3e666003397fb685cd44956d33419219950@seed2.lava.chainlayer.net:26656,1105d3a3384edaa450f4f63c2b1ff08d366ee256@159.203.86.102:26656,f1caeaacfac32e4dd00916e8d912e1d834e94eb3@lava-seed.stakecito.com:26666,e4eb68c6fdfab1575b8794205caed47d4f737df4@lava-mainnet-seed.01node.com:26107,2d4db6b95804ea97e1f3655d043e6becf9bffc94@lava-seeds2.w3coins.io:11156,dcbfb490ea930fe9e8058089e3f6a14ca274c1c4@217.182.136.79:26656,e023c3892862744081360a99a2666e8111b196d3@38.242.213.53:26656,eafff29ec471bdd0985a9360b2c103997539c939@lava-seed.node.monster:26649,6a9a65d92b4820a5d198dd95743aa3059d0d3d4c@seed-lava.hashkey.cloud:26656"
peers:
minimum_gas_price: "0ulava"
custom_port_prefix: 199
# StateSync
snap_rpc: https://lava-rpc.polkachu.com:443

# Custom snapshot url
# snapshot_url:

# [Optional] Prep for upgrade in cosmovisor
upgrade_name: v1.0.1

make_args: install-all
