network: neutron
folder: ".neutrond"
daemon: neutrond
chain_id: neutron-1
node_version: v4.2.0
repo: "https://github.com/neutron-org/neutron"
genesis: "https://raw.githubusercontent.com/neutron-org/mainnet-assets/main/neutron-1-genesis.json"
seeds: "74f3a4a0423e72334f4439b438b29934e5f0dbbd@p2p-xyphion.neutron-1.neutron.org:26656,20e1000e88125698264454a884812746c2eb4807@seeds.lavenderfive.com:19156"
minimum_gas_price: "0untrn"
custom_port_prefix: 191

snap_rpc: https://neutron-rpc.polkachu.com:443

snapshot_url: https://d38wxxfm5q5ouq.cloudfront.net/snapshots/mainnet/prunned_neutron-1_13261822.tar.lz4

upgrade_name: v4.0.1
