network: osmosis
folder: ".osmosisd"
daemon: osmosisd
chain_id: osmosis-1
node_version: v25.0.0
repo: https://github.com/osmosis-labs/osmosis
genesis: "https://github.com/osmosis-labs/networks/raw/main/osmosis-1/genesis.json"
seeds: "20e1000e88125698264454a884812746c2eb4807@seeds.lavenderfive.com:12556,f515a8599b40f0e84dfad935ba414674ab11a668@osmosis.blockpane.com:26656,ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:12556"
custom_port_prefix: 125

upgrade_name: v25

snap_rpc: https://osmosis-rpc.cosmos-apis.com:443
snapshot_url: https://snapshots.polkachu.com/snapshots/osmosis/osmosis_15681698.tar.lz4
