# mainnet
network: quasar
folder: ".quasarnode"
daemon: quasard
chain_id: quasar-1
node_version: v3.0.0
repo: https://github.com/quasar-finance/quasar.git
genesis: https://raw.githubusercontent.com/quasar-finance/networks/main/quasar-1/definitive-genesis.json
minimum_gas_price: "0.01uqsr"
seeds: "babc3f3f7804933265ec9c40ad94f4da8e9e0017@seed.rhinostake.com:18256,ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:18256"
peers: ""
custom_port_prefix: 182

upgrade_name: v3

snap_rpc: https://quasar-rpc.publicnode.com:443

snapshot_url: https://snapshots.polkachu.com/snapshots/quasar/quasar_7480562.tar.lz4

# Horcrux
horcrux_group: horcrux_alpha
sentries:
  - 100.100.1.180
  - 100.100.1.201
