network: router
folder: ".routerd"
daemon: routerd
chain_id: router_9600-1
node_version: latest
# Binary Management
binary: https://raw.githubusercontent.com/router-protocol/router-chain-binary-release/v2.1.6/debian/routerd.tar.gz
binary_processing: targz
binary_name: routerd

repo: https://github.com/router-protocol/router-chain-releases
genesis: https://snapshot.genznodes.dev/router/genesis.json
seeds: ""
peers: "c97d2a916ff399382be76f15312286748a949dbd@3.143.207.169:26656,3f2556a0e390fa6f049e85fc0b27064f9ebdb9d7@57.129.28.26:26656,2ff26a9c46dd5995203549b787ebced431cf7c3e@141.95.102.54:26656,3f8d990dad162818344fe2eba87bb0cfffd5071a@49.12.126.40:26656,12621a780cb2b10a2e5a21c1db1db6a4fce1b235@198.244.167.22:2160,fbb30fa866f318e9e1c48188711526fc69f66d18@188.214.133.174:26656,49e4a20d999fe27868a67fc72bc6bf0e1424a610@188.214.133.133:26656,e90a88795977f7cc24982d5684f0f5a4581cd672@185.8.104.157:26656,a44836418adad0b207469c73e09216831d81edaa@65.109.69.59:23756,51013289faa52643852fcaca73202e0ea1e9ce6a@54.218.202.17:30876,43682395b3c1d18e9a8eed4960962b37d3196b42@213.133.99.244:26656,10fec659763badc3ec55b845c2e6c17a70e77fd5@51.195.104.64:15656"
minimum_gas_price: "0route"
custom_port_prefix: 237

upgrade_name: 2.1.1-nitro-to-2.1.6

# StateSync
snap_rpc: https://router-rpc.genznodes.dev:443
p2p_state_sync: false

# Custom snapshot url
snapshot_url: https://ss.router.nodestake.org/2024-06-27_router_7673099.tar.lz4
