network: sge
folder: ".sge"
daemon: sged
chain_id: sgenet-1
minimum_gas_price: "0.001usge"
node_version: v1.5.3
repo: https://github.com/sge-network/sge
genesis: "https://raw.githubusercontent.com/sge-network/networks/master/mainnet/sgenet-1/genesis.json"
seeds: "babc3f3f7804933265ec9c40ad94f4da8e9e0017@seed.rhinostake.com:17756"
custom_port_prefix: 177

upgrade_name: v1.5.3

snap_rpc: https://sge-rpc.polkachu.com:443
