network: stargaze
folder: ".starsd"
daemon: starsd
chain_id: stargaze-1
node_version: v12.1.0
repo: "https://github.com/public-awesome/stargaze"
genesis: "https://raw.githubusercontent.com/public-awesome/mainnet/main/stargaze-1/genesis.tar.gz"
genesis_processing: targz
seeds: "babc3f3f7804933265ec9c40ad94f4da8e9e0017@seed.rhinostake.com:13756,ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:13756"
custom_port_prefix: 137
# snap_rpc: "https://stargaze-rpc.polkachu.com:443"
snap_rpc: "https://rpc.stargaze-apis.com:443"

# Upgrade name
upgrade_name: v12

snapshot_url: https://snapshots.polkachu.com/snapshots/stargaze/stargaze_11135286.tar.lz4
