network: stride
folder: '.stride'
daemon: strided
chain_id: stride-1
node_version: 'v1.0.2'
repo: https://github.com/Stride-Labs/stride.git
genesis: 'https://raw.githubusercontent.com/Stride-Labs/testnet/infra-test/poolparty/infra/genesis.json'
seeds: 'cb91a11588d66cfd9c01f99541df4978a08e0e39@seedv1.main.stridenet.co:26656,ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:12256'
peers: ''
custom_port_prefix: 122
snap_rpc: 'https://stride-rpc.polkachu.com:443'

# [Optional] Snapshot
snapshot_hour: 8
snapshot_minute: 30
