---
# Scroll Blockchain support structure
# custom_port_prefix: 134
# Ports: p2p: 13403, rpc: 13445, ws: 13446

- name: Create folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ folder }}"
    - "{{ folder }}/scroll-geth"

- name: Create a network
  community.docker.docker_network:
    name: "{{ network }}_net"

- name: Run l2geth container
  community.docker.docker_container:
    name: "{{ execution_container_name }}"
    image: scrolltech/l2geth:scroll-{{ execution_container_version }}
    restart_policy: unless-stopped
    state: started
    stop_timeout: 600
    networks:
      - name: "{{ network }}_net"
    ports:
      # p2p
      - "{{ custom_port_prefix }}03:30303/tcp"
      - "{{ custom_port_prefix }}03:30303/udp"
      # rpc
      - "{{ nebula_internal_ip_addr }}:{{ custom_port_prefix }}45:8545"
      - 127.0.0.1:{{ custom_port_prefix }}45:8545
      - "{{ nebula_internal_ip_addr }}:{{ custom_port_prefix }}46:8546"
      - 127.0.0.1:{{ custom_port_prefix }}46:8546
    volumes:
      - "{{ folder }}/scroll-geth:/scroll-geth"
    command:
      # Scroll chain specific
      - --scroll
      - --l1.endpoint={{ ethereum_l1 }}
      - --l1.confirmations=finalized
      - --rollup.verify
      - --cache.noprefetch
      # General
      - --datadir=/scroll-geth
      - --gcmode=archive
      - --port=30303
      # RPC/WS
      - --http
      - --http.port=8545
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --http.api=eth,net,web3,debug,scroll
      - --ws
      - --ws.port=8546
      - --ws.addr=0.0.0.0
      - --ws.origins=*
      # RMN
      - --rpc.txfeecap=0
