network: neutron
folder: ".neutrond"
daemon: neutrond
chain_id: pion-1
node_version: v5.0.0-rc0
repo: "https://github.com/neutron-org/neutron"
genesis: https://github.com/cosmos/testnets/raw/master/replicated-security/pion-1/pion-1-genesis-without-ccv.json.gz
genesis_processing: "gz"
seeds: "0de4d730b5341d3a83721e1cbb5ce7772e26a400@p2p-falcron.pion-1.ntrn.tech:26656"
minimum_gas_price: "0.02untrn"
custom_port_prefix: 191

upgrade_name: v5.0.0-rc0

snapshot_url: https://snapshots.polkachu.com/testnet-snapshots/neutron/neutron_20246723.tar.lz4
