network: seda
folder: ".sedad"
daemon: sedad
chain_id: seda-1-testnet
node_version: v0.0.7
repo: https://github.com/sedaprotocol/seda-chain
genesis: https://github.com/sedaprotocol/seda-networks/blob/main/testnet/genesis.json
seeds: "ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@testnet-seeds.polkachu.com:25856,babc3f3f7804933265ec9c40ad94f4da8e9e0017@testnet-seed.rhinostake.com:25856"
peers: ""
custom_port_prefix: 258
minimum_gas_price: "100000000000aseda"

snap_rpc: https://seda-testnet-rpc.polkachu.com:443

upgrade_name: v0.0.7
