network: aptos
folder: testnet
repo: https://github.com/aptos-labs/aptos-core
node_version: 46bf19eb4f132b9d8fc19eff3f3334cdf9aa1775 # v1.21.0-rc
genesis_blob: https://raw.githubusercontent.com/aptos-labs/aptos-networks/main/testnet/genesis.blob
waypoint: https://raw.githubusercontent.com/aptos-labs/aptos-networks/main/testnet/waypoint.txt
p2p_port: 6180
p2p_port_vfn: 6182
api_port: 8080

# Build profile
build_profile: release

# Grafana dashboard
dashboardUID: bz8kPr673
# hotfix_binary_url: https://github.com/aptos-labs/aptos-core/releases/download/adhoc-20240209/aptos-node-ubuntu-22.04.tgz
