network: osmosis
folder: ".osmosisd"
daemon: osmosisd
chain_id: osmo-test-5
node_version: v25.0.0-rc0
repo: https://github.com/osmosis-labs/osmosis
genesis: "https://genesis.osmotest5.osmosis.zone/genesis.json"
seeds: "7c2b9e76be5c2142c76b429d9c29e902599ceb44@157.245.21.183:26656,bb197876fd952d245ef6377e3651c157e3d7ed81@157.245.26.231:26656"
peers: ""
custom_port_prefix: 125

upgrade_name: v25

snap_rpc: "https://osmosis-testnet-rpc.polkachu.com:443"

snapshot_url: https://osmosis.fra1.digitaloceanspaces.com/osmo-test-5/snapshots/v20/osmotest5_3901138.tar.lz4
