---
# Base with op-node, op-geth.  Utilized snap-sync for sync
# Per https://github.com/base-org/node/releases
# Base port prefix: 135
# Ports:
#  - Geth: 13503 (p2p - public), 13545 (rpc), 13546 (ws), 8551 (authrpc)
#  - Node: 13509 (p2p - public), 13549 (rpc)

- name: Register public ip
  ansible.builtin.uri:
    url: https://ipv4.icanhazip.com/
    return_content: true
  register: public_ip

- name: Ensure base folders exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ folder }}"
    - "{{ folder }}/base-geth-data"
    - "{{ folder }}/base-node-config"

# - name: Copy node rollup file
#   ansible.builtin.copy:
#     src: "files/rollup-{{ op_network }}.json"
#     dest: "{{ folder }}/base-node-config/rollup.json"
#     mode: "0644"

- name: Create jwtsecret if it does not exist
  ansible.builtin.shell: "openssl rand -hex 32 | tr -d '\n' > jwtsecret"
  args:
    chdir: "{{ user_dir }}/docker-compose"
    creates: jwtsecret
    executable: /bin/bash

- name: Create a network
  community.docker.docker_network:
    name: "{{ network }}_net"
    state: present
    ipam_config:
      - subnet: 172.0.{{ custom_port_prefix }}.0/24
        gateway: 172.0.{{ custom_port_prefix }}.1

- name: Run base-op-geth container
  community.docker.docker_container:
    name: "{{ execution_container_name }}"
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:{{ execution_container_version }}
    restart_policy: unless-stopped
    state: started
    stop_timeout: 600
    pull: true
    networks:
      - name: "{{ network }}_net"
    ports:
      # p2p
      - 13503:13503/tcp
      - 13503:13503/udp
      # rpc
      - 127.0.0.1:13545:8545
      - "{{ nebula_internal_ip_addr }}:13545:8545"
      - 127.0.0.1:13546:8546
      - "{{ nebula_internal_ip_addr }}:13546:8546"
      # metrics
      - 127.0.0.1:13560:6060
      - "{{ nebula_internal_ip_addr }}:13560:6060"
    volumes:
      - "{{ folder }}/base-geth-data:/base-geth-data"
      - "{{ user_dir }}/docker-compose/jwtsecret:/jwtsecret"
      - /etc/localtime:/etc/localtime:ro
    command:
      ## General
      - --datadir=/base-geth-data
      - --syncmode=snap
      - --bootnodes={{ execution_bootnodes }}
      - --op-network={{ execution_network }}
      - --db.engine=pebble # (leveldb or pebble)
      - --state.scheme=hash # (hash or path)
      ## Interfaces
      # Consensus Layer Engine API
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret=/jwtsecret
      # HTTP/RPC
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.corsdomain=*
      - --http.vhosts=*
      - --http.api=web3,debug,eth,txpool,net,engine
      # Websocket
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.origins=*
      - --ws.api=web3,debug,eth,txpool,net,engine
      # P2P
      - --port=13503
      - --discovery.port=13503
      - --nat=extip:{{ public_ip.content | trim }}
      # Metrics
      - --metrics
      - --metrics.addr=0.0.0.0
      - --metrics.port=6060
      # Transaction & Chain Specific
      - --rollup.sequencerhttp={{ execution_sequencerhttp }}
      - --rollup.disabletxpoolgossip=true
      - --rollup.halt=major
      - --rpc.gascap=0
      - --ipcdisable
      - --rpc.batch-response-max-size=70000000 # Per RMN Documentation
      - --rpc.txfeecap=0 # Per RMN Documentation

- name: Run base-op-node container
  community.docker.docker_container:
    name: "{{ consensus_container_name }}"
    image: ghcr.io/base-org/node:{{ consensus_container_version }}
    restart_policy: unless-stopped
    state: started
    stop_timeout: 600
    pull: true
    networks:
      - name: "{{ network }}_net"
    ports:
      # p2p
      - 13509:13509
      # rpc
      - 127.0.0.1:13549:9545
      - "{{ nebula_internal_ip_addr }}:13549:9545"
    volumes:
      # - "{{ folder }}/base-node-config/rollup.json:/rollup.json"
      - "{{ user_dir }}/docker-compose/jwtsecret:/jwtsecret"
      - /etc/localtime:/etc/localtime:ro
    command:
      ## General
      - ./op-node
      - --l1={{ ethereum_l1 }}
      - --l1.beacon={{ ethereum_l1_beacon }}
      - --l1.trustrpc=true
      - --l2=http://{{ execution_container_name }}:8551
      - --l2.jwt-secret=/jwtsecret
      - --network={{ consensus_network }}
      - --rollup.load-protocol-versions=true
      # - --rollup.config=/rollup.json
      # Syncing
      - --syncmode=execution-layer
      - --l1.max-concurrency=64
      - --l1.rpc-rate-limit=0
      - --l1.rpc-max-batch-size=500
      - --verifier.l1-confs=4
      # p2p
      - --p2p.advertise.ip={{ public_ip.content | trim }}
      - --p2p.listen.tcp=13509
      - --p2p.bootnodes={{ consensus_bootnodes }}
      ## Interfaces
      - --rpc.addr=0.0.0.0
      - --rpc.port=9545
