---
# Optimism with op-node, op-geth.  Utilized snap-sync for sync
# Ports:
#  - Geth: 13303 (p2p - public), 13045 (rpc), 13046 (ws), 8551 (authrpc)
#  - Node: 9003 (p2p - public), 9545 (rpc)

- name: Register public ip
  ansible.builtin.uri:
    url: https://ipv4.icanhazip.com/
    return_content: true
  register: public_ip

- name: Ensure op-geth-data exists
  ansible.builtin.file:
    path: "{{ user_dir }}/docker-compose/{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ folder }}"
    - "{{ folder }}/op-geth"

- name: Create jwtsecret if it does not exist
  ansible.builtin.shell: "openssl rand -hex 32 | tr -d '\n' > jwtsecret"
  args:
    chdir: "{{ user_dir }}/docker-compose"
    creates: jwtsecret
    executable: /bin/bash

- name: Create a network
  community.docker.docker_network:
    name: optimism_net

- name: Run op-geth container
  community.docker.docker_container:
    name: "{{ execution_container_name }}"
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:{{ execution_container_version }}
    restart_policy: unless-stopped
    state: started
    stop_timeout: 600
    pull: true
    networks:
      - name: optimism_net
    ports:
      # p2p
      - "{{ custom_port_prefix }}03:{{ custom_port_prefix }}03/tcp"
      - "{{ custom_port_prefix }}03:{{ custom_port_prefix }}03/udp"
      # rpc
      - "127.0.0.1:{{ custom_port_prefix }}45:8545"
      - "{{ nebula_internal_ip_addr }}:{{ custom_port_prefix }}45:8545"
      - "127.0.0.1:{{ custom_port_prefix }}46:8546"
      - "{{ nebula_internal_ip_addr }}:{{ custom_port_prefix }}46:8546"
      # metrics
      - "127.0.0.1:{{ custom_port_prefix }}60:6060"
      - "{{ nebula_internal_ip_addr }}:{{ custom_port_prefix }}60:6060"
    volumes:
      - "{{ folder }}/op-geth:/op-geth-data"
      - "{{ user_dir }}/docker-compose/jwtsecret:/jwtsecret"
      - /etc/localtime:/etc/localtime:ro
    command:
      ## General
      - --datadir=/op-geth-data
      - --gcmode=full
      - --syncmode=snap
      - --op-network=op-mainnet
      - --rollup.halt=major
      - --db.engine=leveldb # or pebble
      - --state.scheme=hash # or hash.  Moving to path based
      ## Interfaces
      # Consensus Layer Engine API
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret=/jwtsecret
      # HTTP/RPC
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.corsdomain=*
      - --http.vhosts=*
      - --http.api=web3,debug,eth,txpool,net,engine
      # Websocket
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.origins=*
      - --ws.api=web3,debug,eth,txpool,net,engine
      # P2P
      - --port={{ custom_port_prefix }}03
      - --nat=extip:{{ public_ip.content | trim }}
      # Metrics
      - --metrics
      - --metrics.addr=0.0.0.0
      - --metrics.port=6060
      # Transaction & Chain Specific
      - --rollup.sequencerhttp=https://mainnet-sequencer.optimism.io
      - --rollup.disabletxpoolgossip=true
      - --ipcdisable
      # RMN
      - --rpc.batch-response-max-size=70000000 # Per RMN Documentation
      - --rpc.txfeecap=0 # Per RMN Documentation

- name: Run op-node container
  community.docker.docker_container:
    name: "{{ consensus_container_name }}"
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:{{ consensus_container_version }}
    restart_policy: unless-stopped
    state: started
    stop_timeout: 600
    pull: true
    networks:
      - name: optimism_net
    ports:
      # p2p
      - "{{ custom_port_prefix }}13:{{ custom_port_prefix }}13"
      # rpc
      - 127.0.0.1:{{ custom_port_prefix }}55:{{ custom_port_prefix }}55
      - "{{ nebula_internal_ip_addr }}:{{ custom_port_prefix }}55:{{ custom_port_prefix }}55"
    volumes:
      - "{{ user_dir }}/docker-compose/jwtsecret:/jwtsecret"
      - /etc/localtime:/etc/localtime:ro
    command:
      ## General
      - op-node
      - --l1={{ ethereum_l1 }}
      - --l1.beacon={{ ethereum_l1_beacon }}
      - --l1.trustrpc
      - --l2=ws://op-geth:8551
      - --l2.jwt-secret=/jwtsecret
      - --l2.enginekind=geth
      - --network=op-mainnet
      # Syncing
      - --syncmode=execution-layer
      - --l1.max-concurrency=64
      - --l1.rpc-rate-limit=0
      - --l1.rpc-max-batch-size=500
      # p2p
      - --p2p.advertise.ip={{ public_ip.content | trim }}
      - --p2p.listen.tcp={{ custom_port_prefix }}13
      ## Interfaces
      - --rpc.addr=0.0.0.0
      - --rpc.port={{ custom_port_prefix }}55
