---
# Astar Blockchain support structure
# custom_port_prefix: 131
# Ports: p2p: 13133, rpc: 13144

- name: Create folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ folder }}"
    - "{{ folder }}/{{ execution_container_name }}"

- name: Create a network
  community.docker.docker_network:
    name: "{{ network }}_net"

- name: Get current user and group
  ansible.builtin.shell:
    cmd: echo "$(id -u):$(id -g)"
  register: current_user

- name: Run astar-collator container
  community.docker.docker_container:
    name: "{{ execution_container_name }}"
    image: staketechnologies/astar-collator:{{ execution_container_version }}
    restart_policy: unless-stopped
    state: started
    stop_timeout: 600
    user: "{{ current_user.stdout }}"
    networks:
      - name: "{{ network }}_net"
    ports:
      # p2p
      - "{{ custom_port_prefix }}33:30333/tcp"
      - "{{ custom_port_prefix }}33:30333/udp"
      # rpc
      - "{{ nebula_internal_ip_addr }}:{{ custom_port_prefix }}44:{{ custom_port_prefix }}44"
      - 127.0.0.1:{{ custom_port_prefix }}44:{{ custom_port_prefix }}44
    volumes:
      - "{{ folder }}/{{ execution_container_name }}:/data"
    command: >
      astar-collator
      --name {{ execution_container_name }}
      --base-path /data
      --chain astar
      --rpc-external
      --rpc-methods Safe
      --rpc-max-request-size 1000
      --rpc-max-response-size 1000
      --rpc-port {{ custom_port_prefix }}44
      --rpc-cors all
      --enable-evm-rpc
      --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0'
      --state-pruning 256
      --blocks-pruning archive-canonical
      --
      --state-pruning 100
      --blocks-pruning 100
      --sync warp
