---
- name: Install unzip
  ansible.builtin.apt:
    name: unzip
    state: present

- name: Download binary
  ansible.builtin.get_url:
    url: "{{ binary }}"
    dest: "/tmp/binary.zip"
    mode: "0700"
    force: true

- name: Unarchive binary
  ansible.builtin.unarchive:
    src: "/tmp/binary.zip"
    remote_src: true
    dest: "/tmp"
    mode: "0644"

- name: Copy binary
  ansible.builtin.copy:
    remote_src: true
    src: "/tmp/{{ daemon }}"
    dest: "{{ user_dir }}/go/bin/{{ daemon }}"
    mode: "0755"
