# Arbitrum versions and approach
network: testnet_arbitrum
folder: "{{ user_dir }}/docker-compose/{{ network }}"
custom_port_prefix: 118

# Execution version
execution_container_name: testnet-arbitrum
execution_container_version: v3.2.0-f847be0
execution_snapshot_location: "{{ folder }}/arbitrum-data/xx"

# Arbitrum specific variables
arbitrum_chain_name: sepolia-rollup
