---
- name: Install ufw
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: true

- name: Open RHINO subnets
  community.general.ufw:
    rule: allow
    src: "{{ item.subnet }}"
    comment: "{{ item.comment }}"
  loop:
    - subnet: 10.0.0.0/8
      comment: Internal - RHINOMgmtVRF
    - subnet: 100.100.0.0/22
      comment: Internal - Nebula
    - subnet: 192.168.0.0/16
      comment: Internal - RemoteMgmt
    - subnet: 38.32.16.56/29
      comment: External - TroyMgmt
    - subnet: 38.146.3.0/24
      comment: External - Troy /24
    - subnet: 104.244.208.240/29
      comment: External - SouthfieldMgmt

- name: Remove outdated ufw rules
  community.general.ufw:
    rule: allow
    src: "{{ item }}"
    delete: true
  loop:
    - 38.146.3.100/31 # Unneeded overlap
    - 172.16.0.0/24 # Internal - Horcrux

- name: Disable root login over SSH
  ansible.builtin.lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: Restart ssh

- name: Disable password login
  ansible.builtin.lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: Restart ssh

- name: Enable firewall
  community.general.ufw:
    state: enabled
