# Polygon versions and approach
network: polygonzkevm
folder: "{{ user_dir }}/docker-compose/{{ network }}"
custom_port_prefix: 119

# Execution
execution_container_name: "{{ network }}-erigon"
execution_container_version: v1.2.24
execution_snapshot_location: "{{ folder }}/chaindata"
